# 1. 베이스 이미지
FROM node:20-alpine

# 2. 작업 디렉토리 설정
WORKDIR /app

# 3. 의존성 설치 (최신 이미지 업데이트 포함)
COPY package.json yarn.lock ./
RUN apk add --no-cache \
  chromium \
  nss \
  freetype \
  harfbuzz \
  ca-certificates \
  ttf-freefont \
  python3 \
  py3-pip && \
  yarn install

# 4. 소스 코드 복사
COPY . .

# 5. Puppeteer 환경 변수 설정
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# 6. 빌드 (TypeScript 사용 시)
RUN yarn build

# 7. 포트 노출
EXPOSE 4000

# 8. 애플리케이션 실행
CMD ["yarn", "start"]
