export const newsData = [
  {
    id: 1,
    source: "BBC News",
    title: "Tech Innovations in 2024",
    summary:
      "New technologies areNew technologies areNew technologies areNew technologies areNew technologies areNew technologies areNew technologies areNew technologies are expected to revolutionize industries by 2024.",
    keywords: ["Technology", "Innovation", "2024"],
  },
  {
    id: 2,
    source: "CNN",
    title: "Climate Change and its Global Impact",
    summary:
      "Scientists warn of severe impacts from climate change on the planet.",
    keywords: ["Climate Change", "Environment", "Science"],
  },
  {
    id: 3,
    source: "Reuters",
    title: "Stock Market Surges",
    summary: "The stock market sees a significant rise in global trading.",
    keywords: ["Stock Market", "Finance", "Global"],
  },
  {
    id: 4,
    source: "Al Jazeera",
    title: "New Space Mission Announced",
    summary: "NASA announces plans for a new mission to Mars by 2025.",
    keywords: ["Space", "NASA", "Mars"],
  },
  {
    id: 5,
    source: "The Guardian",
    title: "Rising Unemployment Rates",
    summary:
      "The global unemployment rate continues to climb in recent months.",
    keywords: ["Economy", "Unemployment", "Global"],
  },
  {
    id: 6,
    source: "The New York Times",
    title: "AI and the Future of Work",
    summary: "AI technology is changing the way businesses and employees work.",
    keywords: ["AI", "Technology", "Workforce"],
  },
  {
    id: 7,
    source: "NBC News",
    title: "Global Health Crisis",
    summary:
      "The WHO warns about the global spread of a new infectious disease.",
    keywords: ["Health", "Pandemic", "WHO"],
  },
  {
    id: 8,
    source: "Forbes",
    title: "Breakthroughs in Renewable Energy",
    summary:
      "New renewable energy sources are paving the way for a cleaner future.",
    keywords: ["Energy", "Renewable", "Climate"],
  },
  {
    id: 9,
    source: "Bloomberg",
    title: "Real Estate Market Decline",
    summary:
      "Housing prices have dropped significantly in several major cities.",
    keywords: ["Real Estate", "Housing", "Market"],
  },
  {
    id: 10,
    source: "The Independent",
    title: "Elections Around the World",
    summary: "Global elections are shaping the future of many countries.",
    keywords: ["Politics", "Elections", "Global"],
  },
  {
    id: 11,
    source: "Time Magazine",
    title: "Rising Costs of Living",
    summary:
      "The cost of living continues to rise in many major urban centers.",
    keywords: ["Economy", "Cost of Living", "Urban"],
  },
  {
    id: 12,
    source: "National Geographic",
    title: "New Discoveries in Deep Ocean",
    summary: "Scientists have found new species in the deep oceans.",
    keywords: ["Science", "Ocean", "Discovery"],
  },
  {
    id: 13,
    source: "HuffPost",
    title: "Global Water Shortage Warnings",
    summary: "A global water shortage is expected to affect billions by 2050.",
    keywords: ["Water", "Environment", "Crisis"],
  },
  {
    id: 14,
    source: "The Wall Street Journal",
    title: "Cryptocurrency Boom",
    summary:
      "Cryptocurrency continues to see growth as more institutions adopt it.",
    keywords: ["Cryptocurrency", "Finance", "Blockchain"],
  },
  {
    id: 15,
    source: "USA Today",
    title: "Sports World Reacts to New Rules",
    summary:
      "New sports rules are being implemented worldwide to improve gameplay.",
    keywords: ["Sports", "Rules", "Global"],
  },
  {
    id: 16,
    source: "The Verge",
    title: "Electric Cars Take the Lead",
    summary: "Electric vehicles are taking over the automotive market in 2024.",
    keywords: ["Electric Cars", "Automotive", "Sustainability"],
  },
  ,
  {
    id: 21,
    source: "BBC News",
    title: "Wildlife Conservation Successes",
    summary: "Efforts to protect endangered species are seeing great results.",
    keywords: ["Wildlife", "Conservation", "Environment"],
  },
  {
    id: 22,
    source: "CNN",
    title: "Medical Breakthroughs in Cancer Research",
    summary: "New treatments offer hope in the fight against cancer.",
    keywords: ["Medicine", "Cancer", "Research"],
  },
  {
    id: 23,
    source: "Reuters",
    title: "International Trade Agreements",
    summary: "Countries sign deals to enhance trade and boost economies.",
    keywords: ["Trade", "Economy", "Global"],
  },
  {
    id: 24,
    source: "Al Jazeera",
    title: "Clean Water Access Improves Globally",
    summary: "Millions gain access to clean drinking water this year.",
    keywords: ["Water", "Health", "Global"],
  },
  {
    id: 25,
    source: "The Guardian",
    title: "Education Systems Reformed",
    summary: "Reforms aim to improve education standards worldwide.",
    keywords: ["Education", "Reform", "Global"],
  },
  {
    id: 26,
    source: "TechCrunch",
    title: "Startups Revolutionizing AI",
    summary: "New startups are leading the charge in AI innovation.",
    keywords: ["AI", "Startups", "Innovation"],
  },
  {
    id: 27,
    source: "BBC News",
    title: "Global Renewable Energy Adoption",
    summary: "Countries are increasing investments in renewable energy.",
    keywords: ["Energy", "Renewable", "Sustainability"],
  },
  {
    id: 28,
    source: "The Guardian",
    title: "Wildfires Threaten Forests",
    summary: "Massive wildfires are causing significant environmental damage.",
    keywords: ["Wildfires", "Environment", "Forests"],
  },
  {
    id: 29,
    source: "National Geographic",
    title: "Ocean Pollution Crisis",
    summary: "Plastic waste in the oceans reaches alarming levels.",
    keywords: ["Pollution", "Ocean", "Environment"],
  },
  {
    id: 30,
    source: "Reuters",
    title: "Economic Growth Trends 2024",
    summary: "Global economies are recovering faster than expected.",
    keywords: ["Economy", "Growth", "2024"],
  },
  {
    id: 31,
    source: "Forbes",
    title: "Women in Leadership Roles",
    summary: "More women are taking on leadership positions in industries.",
    keywords: ["Leadership", "Women", "Equality"],
  },
  {
    id: 32,
    source: "CNN",
    title: "Breakthroughs in Vaccine Technology",
    summary: "New vaccine technologies show promise in disease prevention.",
    keywords: ["Vaccine", "Health", "Science"],
  },
  {
    id: 33,
    source: "NBC News",
    title: "Urbanization and Smart Cities",
    summary:
      "Cities are adopting smart technologies to improve living conditions.",
    keywords: ["Smart Cities", "Urbanization", "Technology"],
  },
  {
    id: 34,
    source: "Bloomberg",
    title: "Oil Prices on the Rise",
    summary: "Oil prices have increased sharply due to geopolitical tensions.",
    keywords: ["Oil", "Economy", "Market"],
  },
  {
    id: 35,
    source: "The Verge",
    title: "Virtual Reality Gaming Boom",
    summary: "Virtual reality games are gaining popularity among players.",
    keywords: ["Gaming", "Virtual Reality", "Technology"],
  },
  {
    id: 36,
    source: "HuffPost",
    title: "Mental Health Awareness Campaigns",
    summary: "Campaigns aim to reduce stigma around mental health issues.",
    keywords: ["Mental Health", "Awareness", "Health"],
  },
  {
    id: 37,
    source: "BBC News",
    title: "Space Tourism Becomes Reality",
    summary: "Commercial space travel is now available for wealthy tourists.",
    keywords: ["Space", "Tourism", "Innovation"],
  },
  {
    id: 38,
    source: "TechRadar",
    title: "Advances in Smartphone Technology",
    summary: "New smartphones feature advanced AI and camera systems.",
    keywords: ["Smartphones", "Technology", "AI"],
  },
  {
    id: 39,
    source: "The Independent",
    title: "Political Reforms Gain Traction",
    summary: "Governments are introducing reforms to improve governance.",
    keywords: ["Politics", "Reforms", "Governance"],
  },
  {
    id: 40,
    source: "The Wall Street Journal",
    title: "Cryptocurrency Regulation Updates",
    summary: "Governments are tightening regulations on digital currencies.",
    keywords: ["Cryptocurrency", "Regulation", "Finance"],
  },
  {
    id: 41,
    source: "Al Jazeera",
    title: "Refugee Crisis Intensifies",
    summary: "Conflict and climate change drive more people to seek asylum.",
    keywords: ["Refugees", "Crisis", "Global"],
  },
  {
    id: 42,
    source: "National Geographic",
    title: "Wildlife Photography Trends",
    summary: "Photographers capture stunning images of endangered species.",
    keywords: ["Photography", "Wildlife", "Conservation"],
  },
  {
    id: 43,
    source: "The Guardian",
    title: "Affordable Housing Solutions",
    summary: "Efforts to provide affordable housing gain momentum worldwide.",
    keywords: ["Housing", "Affordability", "Solutions"],
  },
  {
    id: 44,
    source: "Reuters",
    title: "Electric Vehicle Sales Surge",
    summary: "EVs are becoming more affordable and accessible to consumers.",
    keywords: ["Electric Vehicles", "Automotive", "Sustainability"],
  },
  {
    id: 45,
    source: "Time Magazine",
    title: "Renewed Interest in Local Farming",
    summary:
      "People are turning to local farms for fresh, sustainable produce.",
    keywords: ["Farming", "Sustainability", "Local"],
  },
  {
    id: 46,
    source: "BBC News",
    title: "AI in Education",
    summary: "Artificial intelligence is transforming how students learn.",
    keywords: ["AI", "Education", "Technology"],
  },
  {
    id: 47,
    source: "CNBC",
    title: "Global Trade Policies Evolving",
    summary: "Nations adapt trade policies to modern economic challenges.",
    keywords: ["Trade", "Policy", "Economy"],
  },
  {
    id: 48,
    source: "TechCrunch",
    title: "Drone Deliveries Take Off",
    summary: "Retail companies are deploying drones for faster deliveries.",
    keywords: ["Drones", "Delivery", "Technology"],
  },
  {
    id: 49,
    source: "Forbes",
    title: "Entrepreneurship in Developing Countries",
    summary: "Small businesses thrive in developing economies.",
    keywords: ["Entrepreneurship", "Economy", "Development"],
  },
  {
    id: 50,
    source: "Wired",
    title: "Cybersecurity Threats Increase",
    summary: "Hackers target businesses and governments with advanced attacks.",
    keywords: ["Cybersecurity", "Technology", "Threats"],
  },
];

export const rankingData = [
  {
    id: 1,
    title: "AI Revolutionizing Industries in 2024",
    views: 12500,
  },
  {
    id: 2,
    title: "Global Warming: A Crisis Unfolding",
    views: 14200,
  },
  {
    id: 3,
    title: "Stock Market Trends to Watch This Week",
    views: 9700,
  },
  {
    id: 4,
    title: "How Digital Transformation is Changing Business",
    views: 11000,
  },
  {
    id: 5,
    title: "Exploring the Future of Renewable Energy",
    views: 13400,
  },
  {
    id: 6,
    title: "Top Tech Innovations for 2024",
    views: 8500,
  },
  {
    id: 7,
    title: "Understanding Cryptocurrency in 2024",
    views: 10500,
  },
  {
    id: 8,
    title: "Global Health Trends: What's New in 2024",
    views: 11500,
  },
  {
    id: 9,
    title: "How Remote Work is Changing the Workforce",
    views: 10000,
  },
  {
    id: 10,
    title: "The Rise of Electric Vehicles in 2024",
    views: 12000,
  },
  {
    id: 11,
    title: "AI in Healthcare: Transforming Medicine",
    views: 13500,
  },
  {
    id: 12,
    title: "Impact of Climate Change on Global Agriculture",
    views: 9400,
  },
  {
    id: 13,
    title: "The Future of Social Media: What's Next?",
    views: 8000,
  },
  {
    id: 14,
    title: "Sustainability in Fashion: A Growing Trend",
    views: 10200,
  },
  {
    id: 15,
    title: "The Evolution of Autonomous Vehicles",
    views: 11000,
  },
  {
    id: 16,
    title: "Cybersecurity Threats in 2024: What You Need to Know",
    views: 12000,
  },
  {
    id: 17,
    title: "How Blockchain is Changing the Financial Sector",
    views: 9800,
  },
  {
    id: 18,
    title: "New Trends in Global Politics for 2024",
    views: 13000,
  },
  {
    id: 19,
    title: "The Impact of 5G on Global Communication",
    views: 11100,
  },
  {
    id: 20,
    title: "The Growing Role of Artificial Intelligence in Education",
    views: 9500,
  },
];
